package Logins;

public class AccountDetailsPage extends javax.swing.JDialog {

    /**
     * Creates new form AccountDetailsPage
     */
    public AccountDetailsPage(java.awt.Frame parent, boolean modal, Bank bank, Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        setTitle(String.format("Account Details Page - %s %s", customer.getFirstName(), customer.getLastName()));

        firstNameField.setText(customer.getFirstName());
        lastNameField.setText(customer.getLastName());
        ssnField.setText(customer.getCnp());
        typeField.setText(customer.getAccount().getAccountType().name());
        accountNumberField.setText(String.valueOf(customer.getAccount().getAccountNumber()));
        balanceField.setText(String.format("Lei %.2f", customer.getAccount().getBalance()));
        interestField.setText(String.valueOf(bank.checkInterest(customer.getAccount().getBalance(), 0) * 100) + "%");
        feeField.setText(String.format("Lei %.2f", bank.getTransactionFee(customer.getAccount().getAccountType())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        ssnField = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        accountNumberField = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceField = new javax.swing.JLabel();
        interestLabel = new javax.swing.JLabel();
        interestField = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        feeField = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(9, 2, 5, 5));

        firstNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        firstNameLabel.setText("Prenume:");
        getContentPane().add(firstNameLabel);
        getContentPane().add(firstNameField);

        lastNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lastNameLabel.setText("Nume:");
        getContentPane().add(lastNameLabel);
        getContentPane().add(lastNameField);

        ssnLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ssnLabel.setText("Cnp:");
        getContentPane().add(ssnLabel);
        getContentPane().add(ssnField);

        typeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        typeLabel.setText("Tipul contului:");
        getContentPane().add(typeLabel);
        getContentPane().add(typeField);

        accountNumberLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        accountNumberLabel.setText("Numărul contului:");
        getContentPane().add(accountNumberLabel);
        getContentPane().add(accountNumberField);

        balanceLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        balanceLabel.setText("Bani în cont:");
        getContentPane().add(balanceLabel);
        getContentPane().add(balanceField);

        interestLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        interestLabel.setText("Rata dobânzii:");
        getContentPane().add(interestLabel);
        getContentPane().add(interestField);

        feeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        feeLabel.setText("Comision tranzacție:");
        getContentPane().add(feeLabel);
        getContentPane().add(feeField);

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setForeground(new java.awt.Color(0, 0, 0));
        okButton.setText("OK");
        okButton.setBorder(null);
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberField;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JLabel balanceField;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel feeField;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JLabel firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel interestField;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JLabel lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel ssnField;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JLabel typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
