package bankapp;


import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Carl
 */
public class AddAccountMenu extends javax.swing.JDialog {

    private Bank bank;
    private Customer customer;

    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal, Bank bank) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.bank = bank;
        customer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        cnpField = new javax.swing.JTextField();
        depositLabel = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account Menu");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameLabel.setText("Prenume:");
        getContentPane().add(firstNameLabel);
        getContentPane().add(firstNameField);

        lastNameLabel.setText("Nume:");
        getContentPane().add(lastNameLabel);
        getContentPane().add(lastNameField);

        ssnLabel.setText("Cnp:");
        getContentPane().add(ssnLabel);
        getContentPane().add(cnpField);

        depositLabel.setText("Depozitul inițial:");
        getContentPane().add(depositLabel);
        getContentPane().add(depositField);

        typeLabel.setText("Tipul contului:");
        getContentPane().add(typeLabel);

        typeField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Depozit", "Economii" }));
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(typeField);

        okButton.setText("OK");
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        StringBuilder warnings = new StringBuilder();
        String firstName = "", lastName = "", cnp = "", depositString = "";
        double amount = 0;
        //Verify first name field. Am pus return pentru ca sa nu ma lase sa trec mai departe daca nu completez un camp
        if (firstNameField.getText().isEmpty()) {
            warnings.append("Câmpul prenume nu poate fi gol.\n");
        } else {
            firstName = firstNameField.getText();
        }
        //Daca prenumele este un numar - eroare
        if (firstNameField.getText().matches("-?\\d+(\\.\\d+)?"))
        {
            JOptionPane.showMessageDialog(this, "Nu sunt admise numere în câmpul prenume!","Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         //Verificare pentru litere in campul prenume
        if(!firstNameField.getText().matches("^[a-zA-z0-9]*$"))
        {
            JOptionPane.showMessageDialog(this,"Sunt admise doar litere în câmpul prenume!","Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
      
        //Verificare nume
        if (lastNameField.getText().isEmpty()) {
            warnings.append("Câmpul nume nu poate fi gol.\n");
        } else {
            lastName = lastNameField.getText();
        }
        
        //Daca numele este un numar - eroare
        if(lastNameField.getText().matches("-?\\d+(\\.\\d+)?"))
        {
            JOptionPane.showMessageDialog(this, "Nu sunt admise numere în câmpul nume!","Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Verificare pentru litere in campul nume
        if(!lastNameField.getText().matches("^[a-zA-z0-9]*$"))
        {
            JOptionPane.showMessageDialog(this,"Sunt admise doar litere în câmpul nume!","Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        //Verificare CNP
        if(cnpField.getText().isEmpty())
        {
            warnings.append("Câmpul cnp nu poate fi gol.\n");
        }
        //if cnp it is not a number
        if(!cnpField.getText().matches("-?\\d+(\\.\\d+)?"))
        {
            warnings.append("Sunt admise doar numere în câmpul cnp.\n ");
        } else {
            cnp = cnpField.getText();
        }
        
        //Verificare depozit initial
        if (depositField.getText().isEmpty()) {
            warnings.append("Câmpul depozitul inițial nu poate fi gol.");
        } else {
            try {
                amount = Bank.round(Double.parseDouble(depositField.getText()), 2);
            } catch (NumberFormatException ex) {
                warnings.append("Sunt admise doar numere în câmpul depozitul inițial.");
            }
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        } else {
            AccountType accountType = AccountType.Undefined;
            if (typeField.getSelectedItem().toString() == "Depozit") {
                if (amount >= 500) {
                    accountType = AccountType.Depozit;
                } else {
                    warnings.append("Suma minimă pentru deschiderea unui cont tip depozit este 500Lei");
                }
            } else if (typeField.getSelectedItem().toString() == "Economii") {
                if (amount >= 100) {
                    accountType = AccountType.Economii;
                } else {
                    warnings.append("Suma minimă pentru deschiderea unui cont tip economii este 100Lei");
                }
            }
            if (accountType != AccountType.Undefined) {
                customer = bank.openAccount(firstName, lastName, cnp, accountType, amount);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cnpField;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JComboBox typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    Customer getCustomer() {
        return customer;
    }
}
