/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pozaAutentificarejLabel = new javax.swing.JLabel();
        textAutentificarejLabel = new javax.swing.JLabel();
        autentificareLabel = new javax.swing.JLabel();
        jLabelParola = new javax.swing.JLabel();
        utilizatorJtxt = new javax.swing.JTextField();
        utilizatorLabel = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        reseteazajBtn = new javax.swing.JButton();
        continuajBtnL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autentificare");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        pozaAutentificarejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png")));

        textAutentificarejLabel.setBackground(new java.awt.Color(255, 255, 255));
        textAutentificarejLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAutentificarejLabel.setForeground(new java.awt.Color(255, 255, 255));
        textAutentificarejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textAutentificarejLabel.setText("Te rugăm să te autentifici");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(pozaAutentificarejLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(textAutentificarejLabel)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(pozaAutentificarejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(textAutentificarejLabel)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 520);

        autentificareLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        autentificareLabel.setForeground(new java.awt.Color(102, 102, 102));
        autentificareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autentificareLabel.setText("Autentificare");
        jPanel1.add(autentificareLabel);
        autentificareLabel.setBounds(380, 80, 200, 50);

        jLabelParola.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelParola.setForeground(new java.awt.Color(51, 51, 51));
        jLabelParola.setText("Parolă");
        jPanel1.add(jLabelParola);
        jLabelParola.setBounds(360, 270, 90, 16);

        utilizatorJtxt.setBackground(new java.awt.Color(255, 255, 255));
        utilizatorJtxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        utilizatorJtxt.setForeground(new java.awt.Color(51, 51, 51));
        utilizatorJtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.add(utilizatorJtxt);
        utilizatorJtxt.setBounds(360, 180, 260, 40);

        utilizatorLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        utilizatorLabel.setForeground(new java.awt.Color(51, 51, 51));
        utilizatorLabel.setText("Utilizator");
        jPanel1.add(utilizatorLabel);
        utilizatorLabel.setBounds(360, 160, 90, 16);

        jPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPassword);
        jPassword.setBounds(360, 290, 260, 40);

        reseteazajBtn.setBackground(new java.awt.Color(0, 102, 204));
        reseteazajBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        reseteazajBtn.setForeground(new java.awt.Color(255, 255, 255));
        reseteazajBtn.setText("Resetează");
        reseteazajBtn.setBorder(null);
        reseteazajBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reseteazajBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reseteazajBtnActionPerformed(evt);
            }
        });
        jPanel1.add(reseteazajBtn);
        reseteazajBtn.setBounds(520, 380, 100, 30);

        continuajBtnL.setBackground(new java.awt.Color(0, 102, 204));
        continuajBtnL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        continuajBtnL.setForeground(new java.awt.Color(255, 255, 255));
        continuajBtnL.setText("Continuă");
        continuajBtnL.setBorder(null);
        continuajBtnL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continuajBtnL.setMaximumSize(new java.awt.Dimension(92, 23));
        continuajBtnL.setMinimumSize(new java.awt.Dimension(92, 23));
        continuajBtnL.setPreferredSize(new java.awt.Dimension(92, 23));
        continuajBtnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuajBtnLActionPerformed(evt);
            }
        });
        jPanel1.add(continuajBtnL);
        continuajBtnL.setBounds(360, 380, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(662, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void reseteazajBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reseteazajBtnActionPerformed
        jPassword.setText(null);
        utilizatorJtxt.setText(null);
    }//GEN-LAST:event_reseteazajBtnActionPerformed

    private void continuajBtnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuajBtnLActionPerformed
        String password = jPassword.getText();
        String username = utilizatorJtxt.getText();
        if (password.equalsIgnoreCase("changeit") && (username.equalsIgnoreCase("bogdan"))) {
            utilizatorJtxt.setText(null);
            jPassword.setText(null);
            close();

            menus.MainMenu programBanca = new menus.MainMenu();
            programBanca.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Datele de autentificare sunt gresite!", "Login Error", JOptionPane.ERROR_MESSAGE);
            jPassword.setText(null);
            utilizatorJtxt.setText(null);
        }
    }//GEN-LAST:event_continuajBtnLActionPerformed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String password = jPassword.getText();
            String username = utilizatorJtxt.getText();
            if (password.equalsIgnoreCase("changeit") && (username.equalsIgnoreCase("bogdan"))) {
                utilizatorJtxt.setText(null);
                jPassword.setText(null);
                //O metoda care inchide fereastra de login dupa ce datele au fost introduse corect.
                close();
                //deschide layout-ul cu interfata programului bancar
                menus.MainMenu programBanca = new menus.MainMenu();
                programBanca.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Datele de autentificare sunt gresite!", "Login Error", JOptionPane.ERROR_MESSAGE);
                jPassword.setText(null);
                utilizatorJtxt.setText(null);
            }

        }
    }//GEN-LAST:event_jPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autentificareLabel;
    private javax.swing.JButton continuajBtnL;
    private javax.swing.JLabel jLabelParola;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel pozaAutentificarejLabel;
    private javax.swing.JButton reseteazajBtn;
    private javax.swing.JLabel textAutentificarejLabel;
    private javax.swing.JTextField utilizatorJtxt;
    private javax.swing.JLabel utilizatorLabel;
    // End of variables declaration//GEN-END:variables

    //inchide fereastra de login dupa ce datele au fost introduse corect
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

}
