package com.bogdan;

import javax.swing.JOptionPane;

public class MeniuRetragereBani extends javax.swing.JDialog {

    private Client client;
    private Bank banca;

    public MeniuRetragereBani(java.awt.Frame parent, boolean modal, Bank bank, Client customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.banca = bank;
        this.client = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sumaDeRetrasLabel = new javax.swing.JLabel();
        sumaDeRetrasField = new javax.swing.JTextField();
        retrageButton = new javax.swing.JButton();
        anuleazaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meniu retragere bani");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        sumaDeRetrasLabel.setText("Suma de retras:");
        getContentPane().add(sumaDeRetrasLabel);
        getContentPane().add(sumaDeRetrasField);

        retrageButton.setText("Retrage");
        retrageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retrageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(retrageButton);

        anuleazaButton.setText("Anulează");
        anuleazaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anuleazaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anuleazaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(anuleazaButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anuleazaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anuleazaButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_anuleazaButtonActionPerformed

    private void retrageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrageButtonActionPerformed
        StringBuilder warnings = new StringBuilder();
        if (sumaDeRetrasField.getText().isEmpty()) {
            warnings.append("Adăugați suma de retras.\n");
        } else {
            double amount = 0;
            try {
                amount = Bank.round(Double.parseDouble(sumaDeRetrasField.getText()), 2);
                int result = JOptionPane.showConfirmDialog(this, "Retrageți " + String.format("%.2f", amount) + " lei din cont?\nComision tranzacție: Lei " + String.format("%.2f", banca.getComision(client.getCont().getAccountType())));
                if (result == JOptionPane.OK_OPTION) {
                    try {
                        banca.retrageBani(client.getCont().getNumarCont(), amount);
                        this.dispose();
                    } catch (FonduriInsuficienteException ex) {
                        warnings.append("Fonduri insuficiente pentru a finaliza tranzacția.\n");
                    }
                }
            } catch (NumberFormatException ex) {
                warnings.append("Sunt permise doar numere.\n");
            }
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Withdrawal Warnings", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_retrageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anuleazaButton;
    private javax.swing.JButton retrageButton;
    private javax.swing.JTextField sumaDeRetrasField;
    private javax.swing.JLabel sumaDeRetrasLabel;
    // End of variables declaration//GEN-END:variables
}
